# **1- Transforming**

In [1]:
import pandas as pd
df = pd.read_csv("/content/project1_df.csv")

## **Exploring a DataFrame**

In [2]:
print(df)

          CID         TID  Gender     Age Group        Purchase Date  \
0      943146  5876328741  Female         25-45  30/08/2023 20:27:08
1      180079  1018503182    Male         25-45  23/02/2024 09:33:46
2      337580  3814082218   Other  60 and above  06/03/2022 09:09:50
3      180333  1395204173   Other  60 and above  04/11/2020 04:41:57
4      447553  8009390577    Male         18-25  31/05/2022 17:00:32
...       ...         ...     ...           ...                  ...
54995  295864  5407639888   Other         25-45  23/02/2020 10:42:04
54996  706435  1144029904   Other         18-25  12/07/2021 15:59:21
54997  649435  9587323189    Male         45-60  02/08/2024 09:30:44
54998  982183  5032564481  Female         45-60  05/08/2020 23:57:56
54999  126691  9172953722    Male         25-45  21/07/2022 09:05:18

        Product Category Discount Availed    Discount Name  \
0            Electronics              Yes        FESTIVE50
1            Electronics              Yes  SEASONALOFFER21
2               Clothing              Yes  SEASONALOFFER21
3       Sports & Fitness               No              NaN
4       Sports & Fitness              Yes         WELCOME5
...                  ...              ...              ...
54995        Electronics              Yes  SEASONALOFFER21
54996        Electronics              Yes  SEASONALOFFER21
54997     Home & Kitchen              Yes         NEWYEARS
54998  Beauty and Health              Yes  SEASONALOFFER21
54999  Beauty and Health              Yes         NEWYEARS

       Discount Amount (INR)  Gross Amount   Net Amount   Purchase Method  \
0                      64.30    725.304000   661.004000       Credit Card
1                     175.19   4638.991875  4463.801875       Credit Card
2                     211.54   1986.372575  1774.832575       Credit Card
3                       0.00   5695.612650  5695.612650        Debit Card
4                     439.92   2292.651500  1852.731500       Credit Card
...                      ...           ...          ...               ...
54995                 110.89   2819.907300  2709.017300        Debit Card
54996                 488.59   3891.303900  3402.713900  Cash on Delivery
54997                 417.63   4094.687500  3677.057500       Credit Card
54998                 204.56   3977.473500  3772.913500       Credit Card
54999                 380.81   3703.581900  3322.771900       Credit Card

        Location
0      Ahmedabad
1      Bangalore
2          Delhi
3          Delhi
4          Delhi
...          ...
54995      Other
54996  Bangalore
54997     Mumbai
54998    Kolkata
54999     Mumbai

[55000 rows x 13 columns]

In [3]:
print(df.head())

      CID         TID  Gender     Age Group        Purchase Date  \
0  943146  5876328741  Female         25-45  30/08/2023 20:27:08
1  180079  1018503182    Male         25-45  23/02/2024 09:33:46
2  337580  3814082218   Other  60 and above  06/03/2022 09:09:50
3  180333  1395204173   Other  60 and above  04/11/2020 04:41:57
4  447553  8009390577    Male         18-25  31/05/2022 17:00:32

   Product Category Discount Availed    Discount Name  Discount Amount (INR)  \
0       Electronics              Yes        FESTIVE50                  64.30
1       Electronics              Yes  SEASONALOFFER21                 175.19
2          Clothing              Yes  SEASONALOFFER21                 211.54
3  Sports & Fitness               No              NaN                   0.00
4  Sports & Fitness              Yes         WELCOME5                 439.92

   Gross Amount   Net Amount Purchase Method   Location
0    725.304000   661.004000     Credit Card  Ahmedabad
1   4638.991875  4463.801875     Credit Card  Bangalore
2   1986.372575  1774.832575     Credit Card      Delhi
3   5695.612650  5695.612650      Debit Card      Delhi
4   2292.651500  1852.731500     Credit Card      Delhi

In [5]:
df.head()

,CID,TID,Gender,Age Group,Purchase Date,Product Category,Discount Availed,Discount Name,Discount Amount (INR),Gross Amount,Net Amount,Purchase Method,Location
0,943146,5876328741,Female,25-45,30/08/2023 20:27:08,Electronics,Yes,FESTIVE50,64.30,725.304000,661.004000,Credit Card,Ahmedabad
1,180079,1018503182,Male,25-45,23/02/2024 09:33:46,Electronics,Yes,SEASONALOFFER21,175.19,4638.991875,4463.801875,Credit Card,Bangalore
2,337580,3814082218,Other,60 and above,06/03/2022 09:09:50,Clothing,Yes,SEASONALOFFER21,211.54,1986.372575,1774.832575,Credit Card,Delhi
3,180333,1395204173,Other,60 and above,04/11/2020 04:41:57,Sports & Fitness,No,NaN,0.00,5695.612650,5695.612650,Debit Card,Delhi
4,447553,8009390577,Male,18-25,31/05/2022 17:00:32,Sports & Fitness,Yes,WELCOME5,439.92,2292.651500,1852.731500,Credit Card,Delhi

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55000 entries, 0 to 54999
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   CID                    55000 non-null  int64
 1   TID                    55000 non-null  int64
 2   Gender                 55000 non-null  object
 3   Age Group              55000 non-null  object
 4   Purchase Date          55000 non-null  object
 5   Product Category       55000 non-null  object
 6   Discount Availed       55000 non-null  object
 7   Discount Name          27415 non-null  object
 8   Discount Amount (INR)  55000 non-null  float64
 9   Gross Amount           55000 non-null  float64
 10  Net Amount             55000 non-null  float64
 11  Purchase Method        55000 non-null  object
 12  Location               55000 non-null  object
dtypes: float64(3), int64(2), object(8)
memory usage: 5.5+ MB

In [8]:
df.describe()

,CID,TID,Discount Amount (INR),Gross Amount,Net Amount
count,55000.000000,5.500000e+04,55000.000000,55000.000000,55000.000000
mean,551245.593891,5.504740e+09,136.986796,3012.936606,2875.949810
std,260603.330337,2.594534e+09,165.375502,1718.431066,1726.127778
min,100009.000000,1.000163e+09,0.000000,136.454325,-351.119775
25%,323717.000000,3.252604e+09,0.000000,1562.111325,1429.551863
50%,550088.500000,5.498383e+09,0.000000,2954.266150,2814.910875
75%,776955.750000,7.747933e+09,274.115000,4342.221675,4211.407838
max,999996.000000,9.999393e+09,500.000000,8394.825600,8394.825600

In [11]:
df.shape # (rows , columns)

(55000, 13)

In [12]:
print(df.to_numpy())

[[943146 5876328741 'Female' ... 661.004 'Credit Card' 'Ahmedabad']
 [180079 1018503182 'Male' ... 4463.801875 'Credit Card' 'Bangalore']
 [337580 3814082218 'Other' ... 1774.8325749999997 'Credit Card' 'Delhi']
 ...
 [649435 9587323189 'Male' ... 3677.0575 'Credit Card' 'Mumbai']
 [982183 5032564481 'Female' ... 3772.913500000001 'Credit Card'
  'Kolkata']
 [126691 9172953722 'Male' ... 3322.7719 'Credit Card' 'Mumbai']]

In [13]:
print(df.columns)

Index(['CID', 'TID', 'Gender', 'Age Group', 'Purchase Date',
       'Product Category', 'Discount Availed', 'Discount Name',
       'Discount Amount (INR)', 'Gross Amount', 'Net Amount',
       'Purchase Method', 'Location'],
      dtype='object')

In [14]:
print(df.index)

RangeIndex(start=0, stop=55000, step=1)

## **Sorting**

In [15]:
df.sort_values("Gross Amount") # small to big

,CID,TID,Gender,Age Group,Purchase Date,Product Category,Discount Availed,Discount Name,Discount Amount (INR),Gross Amount,Net Amount,Purchase Method,Location
37352,570046,1964089589,Female,25-45,18/02/2020 02:14:13,Beauty and Health,No,NaN,0.00,136.454325,136.454325,Credit Card,Varanasi
17568,262070,5537538360,Female,under 18,01/02/2020 00:15:47,Electronics,Yes,NEWYEARS,429.60,138.890850,-290.709150,Credit Card,Mumbai
38606,481252,9891577351,Female,25-45,03/02/2020 07:18:59,Clothing,Yes,SEASONALOFFER21,413.14,140.461650,-272.678350,Google Pay UPI,Hyderabad
40677,376537,8659700479,Female,25-45,14/01/2020 19:49:31,Clothing,No,NaN,0.00,141.957900,141.957900,Google Pay UPI,Varanasi
48164,386840,8029271119,Female,18-25,20/02/2020 14:18:22,Electronics,Yes,NEWYEARS,352.96,142.077075,-210.882925,Credit Card,Ahmedabad
...,...,...,...,...,...,...,...,...,...,...,...,...,...
52533,675956,7090926391,Female,under 18,01/12/2023 07:55:47,Electronics,Yes,SEASONALOFFER21,214.33,8334.009600,8119.679600,Debit Card,Chennai
5521,255607,7392860072,Male,18-25,15/12/2023 15:55:16,Clothing,No,NaN,0.00,8361.225600,8361.225600,Credit Card,Mumbai
29249,871976,7829441574,Female,25-45,19/12/2023 09:49:50,Toys & Games,Yes,FESTIVE50,492.56,8365.190400,7872.630400,Net Banking,Delhi
21848,738513,7204773289,Female,18-25,06/12/2023 04:26:33,Beauty and Health,No,NaN,0.00,8382.796800,8382.796800,Debit Card,Delhi
26874,202767,5202191880,Other,18-25,11/12/2023 11:19:48,Home & Kitchen,No,NaN,0.00,8394.825600,8394.825600,Debit Card,Pune

In [16]:
df.sort_values("Gross Amount", ascending=False) # big to small

,CID,TID,Gender,Age Group,Purchase Date,Product Category,Discount Availed,Discount Name,Discount Amount (INR),Gross Amount,Net Amount,Purchase Method,Location
26874,202767,5202191880,Other,18-25,11/12/2023 11:19:48,Home & Kitchen,No,NaN,0.00,8394.825600,8394.825600,Debit Card,Pune
21848,738513,7204773289,Female,18-25,06/12/2023 04:26:33,Beauty and Health,No,NaN,0.00,8382.796800,8382.796800,Debit Card,Delhi
29249,871976,7829441574,Female,25-45,19/12/2023 09:49:50,Toys & Games,Yes,FESTIVE50,492.56,8365.190400,7872.630400,Net Banking,Delhi
5521,255607,7392860072,Male,18-25,15/12/2023 15:55:16,Clothing,No,NaN,0.00,8361.225600,8361.225600,Credit Card,Mumbai
52533,675956,7090926391,Female,under 18,01/12/2023 07:55:47,Electronics,Yes,SEASONALOFFER21,214.33,8334.009600,8119.679600,Debit Card,Chennai
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48164,386840,8029271119,Female,18-25,20/02/2020 14:18:22,Electronics,Yes,NEWYEARS,352.96,142.077075,-210.882925,Credit Card,Ahmedabad
40677,376537,8659700479,Female,25-45,14/01/2020 19:49:31,Clothing,No,NaN,0.00,141.957900,141.957900,Google Pay UPI,Varanasi
38606,481252,9891577351,Female,25-45,03/02/2020 07:18:59,Clothing,Yes,SEASONALOFFER21,413.14,140.461650,-272.678350,Google Pay UPI,Hyderabad
17568,262070,5537538360,Female,under 18,01/02/2020 00:15:47,Electronics,Yes,NEWYEARS,429.60,138.890850,-290.709150,Credit Card,Mumbai
37352,570046,1964089589,Female,25-45,18/02/2020 02:14:13,Beauty and Health,No,NaN,0.00,136.454325,136.454325,Credit Card,Varanasi

In [17]:
# Sorting multiple variables
df.sort_values(["Gross Amount","Net Amount"]) # small to big

,CID,TID,Gender,Age Group,Purchase Date,Product Category,Discount Availed,Discount Name,Discount Amount (INR),Gross Amount,Net Amount,Purchase Method,Location
37352,570046,1964089589,Female,25-45,18/02/2020 02:14:13,Beauty and Health,No,NaN,0.00,136.454325,136.454325,Credit Card,Varanasi
17568,262070,5537538360,Female,under 18,01/02/2020 00:15:47,Electronics,Yes,NEWYEARS,429.60,138.890850,-290.709150,Credit Card,Mumbai
38606,481252,9891577351,Female,25-45,03/02/2020 07:18:59,Clothing,Yes,SEASONALOFFER21,413.14,140.461650,-272.678350,Google Pay UPI,Hyderabad
40677,376537,8659700479,Female,25-45,14/01/2020 19:49:31,Clothing,No,NaN,0.00,141.957900,141.957900,Google Pay UPI,Varanasi
48164,386840,8029271119,Female,18-25,20/02/2020 14:18:22,Electronics,Yes,NEWYEARS,352.96,142.077075,-210.882925,Credit Card,Ahmedabad
...,...,...,...,...,...,...,...,...,...,...,...,...,...
52533,675956,7090926391,Female,under 18,01/12/2023 07:55:47,Electronics,Yes,SEASONALOFFER21,214.33,8334.009600,8119.679600,Debit Card,Chennai
5521,255607,7392860072,Male,18-25,15/12/2023 15:55:16,Clothing,No,NaN,0.00,8361.225600,8361.225600,Credit Card,Mumbai
29249,871976,7829441574,Female,25-45,19/12/2023 09:49:50,Toys & Games,Yes,FESTIVE50,492.56,8365.190400,7872.630400,Net Banking,Delhi
21848,738513,7204773289,Female,18-25,06/12/2023 04:26:33,Beauty and Health,No,NaN,0.00,8382.796800,8382.796800,Debit Card,Delhi
26874,202767,5202191880,Other,18-25,11/12/2023 11:19:48,Home & Kitchen,No,NaN,0.00,8394.825600,8394.825600,Debit Card,Pune

In [18]:
# Sorting multiple variables
df.sort_values(["Gross Amount","Net Amount"], ascending = [True, False])

,CID,TID,Gender,Age Group,Purchase Date,Product Category,Discount Availed,Discount Name,Discount Amount (INR),Gross Amount,Net Amount,Purchase Method,Location
37352,570046,1964089589,Female,25-45,18/02/2020 02:14:13,Beauty and Health,No,NaN,0.00,136.454325,136.454325,Credit Card,Varanasi
17568,262070,5537538360,Female,under 18,01/02/2020 00:15:47,Electronics,Yes,NEWYEARS,429.60,138.890850,-290.709150,Credit Card,Mumbai
38606,481252,9891577351,Female,25-45,03/02/2020 07:18:59,Clothing,Yes,SEASONALOFFER21,413.14,140.461650,-272.678350,Google Pay UPI,Hyderabad
40677,376537,8659700479,Female,25-45,14/01/2020 19:49:31,Clothing,No,NaN,0.00,141.957900,141.957900,Google Pay UPI,Varanasi
48164,386840,8029271119,Female,18-25,20/02/2020 14:18:22,Electronics,Yes,NEWYEARS,352.96,142.077075,-210.882925,Credit Card,Ahmedabad
...,...,...,...,...,...,...,...,...,...,...,...,...,...
52533,675956,7090926391,Female,under 18,01/12/2023 07:55:47,Electronics,Yes,SEASONALOFFER21,214.33,8334.009600,8119.679600,Debit Card,Chennai
5521,255607,7392860072,Male,18-25,15/12/2023 15:55:16,Clothing,No,NaN,0.00,8361.225600,8361.225600,Credit Card,Mumbai
29249,871976,7829441574,Female,25-45,19/12/2023 09:49:50,Toys & Games,Yes,FESTIVE50,492.56,8365.190400,7872.630400,Net Banking,Delhi
21848,738513,7204773289,Female,18-25,06/12/2023 04:26:33,Beauty and Health,No,NaN,0.00,8382.796800,8382.796800,Debit Card,Delhi
26874,202767,5202191880,Other,18-25,11/12/2023 11:19:48,Home & Kitchen,No,NaN,0.00,8394.825600,8394.825600,Debit Card,Pune

#**Subsetting Rows**

In [19]:
df["Gross Amount"] < 142

0        False
1        False
2        False
3        False
4        False
         ...
54995    False
54996    False
54997    False
54998    False
54999    False
Name: Gross Amount, Length: 55000, dtype: bool

In [25]:
low = df[df["Gross Amount"] < 142]
low

,CID,TID,Gender,Age Group,Purchase Date,Product Category,Discount Availed,Discount Name,Discount Amount (INR),Gross Amount,Net Amount,Purchase Method,Location
17568,262070,5537538360,Female,under 18,01/02/2020 00:15:47,Electronics,Yes,NEWYEARS,429.60,138.890850,-290.709150,Credit Card,Mumbai
37352,570046,1964089589,Female,25-45,18/02/2020 02:14:13,Beauty and Health,No,NaN,0.00,136.454325,136.454325,Credit Card,Varanasi
38606,481252,9891577351,Female,25-45,03/02/2020 07:18:59,Clothing,Yes,SEASONALOFFER21,413.14,140.461650,-272.678350,Google Pay UPI,Hyderabad
40677,376537,8659700479,Female,25-45,14/01/2020 19:49:31,Clothing,No,NaN,0.00,141.957900,141.957900,Google Pay UPI,Varanasi

In [26]:
category = df[df["Product Category"] == "Clothing"]
category

,CID,TID,Gender,Age Group,Purchase Date,Product Category,Discount Availed,Discount Name,Discount Amount (INR),Gross Amount,Net Amount,Purchase Method,Location
2,337580,3814082218,Other,60 and above,06/03/2022 09:09:50,Clothing,Yes,SEASONALOFFER21,211.54,1986.372575,1774.832575,Credit Card,Delhi
5,200614,3994452858,Male,18-25,12/07/2021 15:10:27,Clothing,Yes,FESTIVE50,127.01,3649.397400,3522.387400,Credit Card,Delhi
9,889269,1342270638,Other,60 and above,18/12/2023 19:04:02,Clothing,Yes,SAVE10,437.50,1497.350400,1059.850400,Credit Card,Bangalore
10,931578,5168806107,Other,25-45,09/12/2022 19:54:47,Clothing,No,NaN,0.00,7824.165300,7824.165300,Credit Card,Other
24,745014,9202622469,Male,18-25,04/05/2023 18:06:02,Clothing,Yes,SAVE10,75.72,3579.912000,3504.192000,Credit Card,Mumbai
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54978,299659,8452038397,Male,45-60,17/03/2022 02:17:29,Clothing,No,NaN,0.00,5295.544150,5295.544150,PhonePe UPI,Delhi
54982,636391,7155237771,Other,45-60,17/06/2021 22:27:20,Clothing,No,NaN,0.00,2586.474000,2586.474000,International Card,Delhi
54986,915197,5506311767,Female,25-45,06/03/2023 15:57:05,Clothing,Yes,SEASONALOFFER21,489.26,2425.122000,1935.862000,Cash on Delivery,Mumbai
54988,566532,7802706084,Male,45-60,02/11/2023 13:06:41,Clothing,No,NaN,0.00,2182.424400,2182.424400,Net Banking,Delhi
54989,812597,3862962312,Male,45-60,07/08/2022 11:42:13,Clothing,No,NaN,0.00,2335.098000,2335.098000,Credit Card,Pune

In [27]:
# Subsetting based on multiple conditions
is_closing = df["Product Category"] == "Clothing"
is_female = df['Gender'] == "Male"
clothing_Male = df[is_closing & is_female]
clothing_Male

,CID,TID,Gender,Age Group,Purchase Date,Product Category,Discount Availed,Discount Name,Discount Amount (INR),Gross Amount,Net Amount,Purchase Method,Location
5,200614,3994452858,Male,18-25,12/07/2021 15:10:27,Clothing,Yes,FESTIVE50,127.01,3649.39740,3522.38740,Credit Card,Delhi
24,745014,9202622469,Male,18-25,04/05/2023 18:06:02,Clothing,Yes,SAVE10,75.72,3579.91200,3504.19200,Credit Card,Mumbai
63,616643,3321212528,Male,18-25,02/05/2020 14:45:06,Clothing,No,NaN,0.00,694.95300,694.95300,Debit Card,Pune
69,826229,3364820508,Male,18-25,17/03/2021 01:34:33,Clothing,No,NaN,0.00,1939.81260,1939.81260,Debit Card,Other
73,508396,5157819119,Male,18-25,25/08/2021 19:19:30,Clothing,No,NaN,0.00,773.65200,773.65200,Debit Card,Mumbai
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54965,373817,4063529299,Male,18-25,06/11/2021 23:19:43,Clothing,Yes,SEASONALOFFER21,82.63,3599.88200,3517.25200,Net Banking,Hyderabad
54974,932685,3920962826,Male,25-45,18/07/2020 09:25:45,Clothing,Yes,SEASONALOFFER21,113.78,2511.84780,2398.06780,Debit Card,Pune
54978,299659,8452038397,Male,45-60,17/03/2022 02:17:29,Clothing,No,NaN,0.00,5295.54415,5295.54415,PhonePe UPI,Delhi
54988,566532,7802706084,Male,45-60,02/11/2023 13:06:41,Clothing,No,NaN,0.00,2182.42440,2182.42440,Net Banking,Delhi
54989,812597,3862962312,Male,45-60,07/08/2022 11:42:13,Clothing,No,NaN,0.00,2335.09800,2335.09800,Credit Card,Pune

In [28]:
# Subsetting using .isin()
categories = df["Product Category"].isin(["Electronics","Clothing"])
categories

0         True
1         True
2         True
3        False
4        False
         ...
54995     True
54996     True
54997    False
54998    False
54999    False
Name: Product Category, Length: 55000, dtype: bool

## **Adding New columns**

In [29]:
df["percentage"] =df['Gross Amount'] / 100
df["percentage"]

0         7.253040
1        46.389919
2        19.863726
3        56.956127
4        22.926515
           ...
54995    28.199073
54996    38.913039
54997    40.946875
54998    39.774735
54999    37.035819
Name: percentage, Length: 55000, dtype: float64

In [30]:
df.head()

,CID,TID,Gender,Age Group,Purchase Date,Product Category,Discount Availed,Discount Name,Discount Amount (INR),Gross Amount,Net Amount,Purchase Method,Location,percentage
0,943146,5876328741,Female,25-45,30/08/2023 20:27:08,Electronics,Yes,FESTIVE50,64.30,725.304000,661.004000,Credit Card,Ahmedabad,7.253040
1,180079,1018503182,Male,25-45,23/02/2024 09:33:46,Electronics,Yes,SEASONALOFFER21,175.19,4638.991875,4463.801875,Credit Card,Bangalore,46.389919
2,337580,3814082218,Other,60 and above,06/03/2022 09:09:50,Clothing,Yes,SEASONALOFFER21,211.54,1986.372575,1774.832575,Credit Card,Delhi,19.863726
3,180333,1395204173,Other,60 and above,04/11/2020 04:41:57,Sports & Fitness,No,NaN,0.00,5695.612650,5695.612650,Debit Card,Delhi,56.956127
4,447553,8009390577,Male,18-25,31/05/2022 17:00:32,Sports & Fitness,Yes,WELCOME5,439.92,2292.651500,1852.731500,Credit Card,Delhi,22.926515