# **Data Manipulation in python**

## 1 - Data Aggregation

## Summary statistics

In [4]:
import pandas as pd
E_commerce= pd.read_csv("/project1_df.csv")

E_commerce

,CID,TID,Gender,Age Group,Purchase Date,Product Category,Discount Availed,Discount Name,Discount Amount (INR),Gross Amount,Net Amount,Purchase Method,Location
0,943146,5876328741,Female,25-45,30/08/2023 20:27:08,Electronics,Yes,FESTIVE50,64.30,725.304000,661.004000,Credit Card,Ahmedabad
1,180079,1018503182,Male,25-45,23/02/2024 09:33:46,Electronics,Yes,SEASONALOFFER21,175.19,4638.991875,4463.801875,Credit Card,Bangalore
2,337580,3814082218,Other,60 and above,06/03/2022 09:09:50,Clothing,Yes,SEASONALOFFER21,211.54,1986.372575,1774.832575,Credit Card,Delhi
3,180333,1395204173,Other,60 and above,04/11/2020 04:41:57,Sports & Fitness,No,NaN,0.00,5695.612650,5695.612650,Debit Card,Delhi
4,447553,8009390577,Male,18-25,31/05/2022 17:00:32,Sports & Fitness,Yes,WELCOME5,439.92,2292.651500,1852.731500,Credit Card,Delhi
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54995,295864,5407639888,Other,25-45,23/02/2020 10:42:04,Electronics,Yes,SEASONALOFFER21,110.89,2819.907300,2709.017300,Debit Card,Other
54996,706435,1144029904,Other,18-25,12/07/2021 15:59:21,Electronics,Yes,SEASONALOFFER21,488.59,3891.303900,3402.713900,Cash on Delivery,Bangalore
54997,649435,9587323189,Male,45-60,02/08/2024 09:30:44,Home & Kitchen,Yes,NEWYEARS,417.63,4094.687500,3677.057500,Credit Card,Mumbai
54998,982183,5032564481,Female,45-60,05/08/2020 23:57:56,Beauty and Health,Yes,SEASONALOFFER21,204.56,3977.473500,3772.913500,Credit Card,Kolkata
54999,126691,9172953722,Male,25-45,21/07/2022 09:05:18,Beauty and Health,Yes,NEWYEARS,380.81,3703.581900,3322.771900,Credit Card,Mumbai

As you can see here, the flow is straightforward: data lives in a source (a database, cloud storage, etc.), gets exported to a data file like a CSV, and then Python loads it into a DataFrame to produce insights.

### **Data Source  ->  Data files  ->  R or Python  -> Insights**

In [5]:

"""The syntax E_commerse['Gross Amount'] on line 1 is how you pull any column out of
 a DataFrame — just put the column name in quotes inside square brackets.
 The result gets stored in the variable amounts """
amounts = E_commerce['Gross Amount']
amounts

0         725.304000
1        4638.991875
2        1986.372575
3        5695.612650
4        2292.651500
            ...
54995    2819.907300
54996    3891.303900
54997    4094.687500
54998    3977.473500
54999    3703.581900
Name: Gross Amount, Length: 55000, dtype: float64

In [6]:
from numpy._core.fromnumeric import mean
"""1 - Data Aggregation"""
# This pattern — target.method(parameters) —
# is consistent across all pandas operations, so it's worth having firmly in mind.

# 1 - What's the Total order amount? Sum()
revenue = amounts.sum()
print(revenue)

# 2 - What's the smallest order amount? → min()
minimum_amount = amounts.min()
print(minimum_amount)

# 3 - What's the largest order amount? → max()
maximum_amount = amounts.max()
print(maximum_amount)

# 4 - What's the average order amount? → mean()
mean_amount = amounts.mean()
print(mean_amount)

165711513.328525
136.45432499999998
8394.8256
3012.936605973182

In [7]:
"""The Difference between median and mean"""
# Mean : sum of all values divided by the count. Every value contributes, including extreme ones.

# 5 - Median :  the middle value when data is sorted. It ignores how extreme the outliers are.

"""
When to use each:

Use median :
 when outliers could distort the picture (e.g., income, house prices
 , order amounts with a few huge corporate orders)


Use mean when there are no significant outliers, or when you specifically want
all values — including extremes — to influence the result
"""

# if the mean was close to median which tells us there aren't major outliers skewing the data in this dataset
median_amount = amounts.median()
print(median_amount)

2954.2661500000004

In [8]:
# 6 - Variance .var()

# 7 - Standard deviation .std()

In [15]:
""" Comulative statistics """
# that the operation be on the current value and the previos values
# .cum
# .cumsum()  -> that the result of any value is its value + all previos values
print(amounts.cumsum())

# .cummin()  ->
print(amounts.cummin()) # the minimum of the series from begin to the index you give

# .cummax()  ->
print(amounts.cummax()) # the maximim of the series from begin to the index you give

# .cumprod()  -> that the result of any value is its value * all previos values
print(amounts.cumprod())

0        7.253040e+02
1        5.364296e+03
2        7.350668e+03
3        1.304628e+04
4        1.533893e+04
             ...
54995    1.656958e+08
54996    1.656997e+08
54997    1.657038e+08
54998    1.657078e+08
54999    1.657115e+08
Name: Gross Amount, Length: 55000, dtype: float64
0        725.304000
1        725.304000
2        725.304000
3        725.304000
4        725.304000
            ...
54995    136.454325
54996    136.454325
54997    136.454325
54998    136.454325
54999    136.454325
Name: Gross Amount, Length: 55000, dtype: float64
0         725.304000
1        4638.991875
2        4638.991875
3        5695.612650
4        5695.612650
            ...
54995    8394.825600
54996    8394.825600
54997    8394.825600
54998    8394.825600
54999    8394.825600
Name: Gross Amount, Length: 55000, dtype: float64
0        7.253040e+02
1        3.364679e+06
2        6.683507e+09
3        3.806667e+13
4        8.727360e+16
             ...
54995             inf
54996             inf
54997             inf
54998             inf
54999             inf
Name: Gross Amount, Length: 55000, dtype: float64

In [25]:
"""What Does .agg() Do in Pandas?"""
# The .agg() (short for aggregate) method in Pandas is used to compute summary statistics
# on your DataFrame or Series. It provides flexibility by allowing you to apply custom functions,
# calculate statistics across multiple columns, or run multiple summary operations all at once.

## using many of basic operation in one call
print(amounts.agg(['min', 'max', 'mean']))

# using a custom operation(function) in one call
# A custom IQR function
def iqr(column):
    return column.quantile(0.75) - column.quantile(0.25)

# Print IQR of the amounts
print(amounts.agg(iqr))

## Using it for multiple columns
print(E_commerce[["Gross Amount","Discount Amount (INR)","Net Amount"]].agg(iqr))
print(E_commerce[["Gross Amount","Discount Amount (INR)","Net Amount"]].agg(["max", "mean"]))
print(E_commerce[["Gross Amount","Discount Amount (INR)","Net Amount"]].agg(["max", "mean",iqr]))

min      136.454325
max     8394.825600
mean    3012.936606
Name: Gross Amount, dtype: float64
2780.110350000001
Gross Amount             2780.110350
Discount Amount (INR)     274.115000
Net Amount               2781.855975
dtype: float64
      Gross Amount  Discount Amount (INR)  Net Amount
max    8394.825600             500.000000  8394.82560
mean   3012.936606             136.986796  2875.94981
      Gross Amount  Discount Amount (INR)   Net Amount
max    8394.825600             500.000000  8394.825600
mean   3012.936606             136.986796  2875.949810
iqr    2780.110350             274.115000  2781.855975

In [18]:
# DataFrame.head()
E_commerce.head()

,CID,TID,Gender,Age Group,Purchase Date,Product Category,Discount Availed,Discount Name,Discount Amount (INR),Gross Amount,Net Amount,Purchase Method,Location
0,943146,5876328741,Female,25-45,30/08/2023 20:27:08,Electronics,Yes,FESTIVE50,64.30,725.304000,661.004000,Credit Card,Ahmedabad
1,180079,1018503182,Male,25-45,23/02/2024 09:33:46,Electronics,Yes,SEASONALOFFER21,175.19,4638.991875,4463.801875,Credit Card,Bangalore
2,337580,3814082218,Other,60 and above,06/03/2022 09:09:50,Clothing,Yes,SEASONALOFFER21,211.54,1986.372575,1774.832575,Credit Card,Delhi
3,180333,1395204173,Other,60 and above,04/11/2020 04:41:57,Sports & Fitness,No,NaN,0.00,5695.612650,5695.612650,Debit Card,Delhi
4,447553,8009390577,Male,18-25,31/05/2022 17:00:32,Sports & Fitness,Yes,WELCOME5,439.92,2292.651500,1852.731500,Credit Card,Delhi

In [30]:
# DataFrame.info()
E_commerce.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55000 entries, 0 to 54999
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   CID                    55000 non-null  int64
 1   TID                    55000 non-null  int64
 2   Gender                 55000 non-null  object
 3   Age Group              55000 non-null  object
 4   Purchase Date          55000 non-null  object
 5   Product Category       55000 non-null  object
 6   Discount Availed       55000 non-null  object
 7   Discount Name          27415 non-null  object
 8   Discount Amount (INR)  55000 non-null  float64
 9   Gross Amount           55000 non-null  float64
 10  Net Amount             55000 non-null  float64
 11  Purchase Method        55000 non-null  object
 12  Location               55000 non-null  object
dtypes: float64(3), int64(2), object(8)
memory usage: 5.5+ MB

In [21]:
"""
Whenever you design a data aggregation, answer two questions:

Which column do we wish to summarize? — For total revenue,
it was amount. For total distance, it was distance. The column
should contain the values relevant to your question.
Which summary operation do we wish to apply? — As you can see here,
the same column can feed into sum, mean, min, or max depending on what insight you need.
These two questions — column and operation — are all you need to design
any aggregation. The rest is just syntax.
"""

'\nWhenever you design a data aggregation, answer two questions:\n\nWhich column do we wish to summarize? — For total revenue, \nit was amount. For total distance, it was distance. The column \nshould contain the values relevant to your question.\nWhich summary operation do we wish to apply? — As you can see here, \nthe same column can feed into sum, mean, min, or max depending on what insight you need.\nThese two questions — column and operation — are all you need to design \nany aggregation. The rest is just syntax.\n'

In [31]:
# count()
# count() counts all non-null values in the column, giving us the total number of rows
Transform_count = E_commerce['TID'].count()
print(Transform_count)

# nunique()
# nunique() scans the user_id column, identifies all distinct values, and counts
# only those — duplicates are ignored entirely.
customer_count = E_commerce['CID'].nunique()
print(customer_count)

# counting
# value_count()
E_commerce["Purchase Method"].value_counts()

# value_count(sort = True)
E_commerce["Purchase Method"].value_counts(sort = True)
# show me the values with sorting

55000
29071

Purchase Method
Credit Card           22096
Debit Card            13809
Net Banking            5485
International Card     2815
Cash on Delivery       2768
PhonePe UPI            2683
Paytm UPI              2674
Google Pay UPI         2670
Name: count, dtype: int64

In [29]:
"""Droping"""
E_commerce.drop_duplicates(subset = "CID")
E_commerce.drop_duplicates(subset = ["CID" , "TID"])

,CID,TID,Gender,Age Group,Purchase Date,Product Category,Discount Availed,Discount Name,Discount Amount (INR),Gross Amount,Net Amount,Purchase Method,Location
0,943146,5876328741,Female,25-45,30/08/2023 20:27:08,Electronics,Yes,FESTIVE50,64.30,725.304000,661.004000,Credit Card,Ahmedabad
1,180079,1018503182,Male,25-45,23/02/2024 09:33:46,Electronics,Yes,SEASONALOFFER21,175.19,4638.991875,4463.801875,Credit Card,Bangalore
2,337580,3814082218,Other,60 and above,06/03/2022 09:09:50,Clothing,Yes,SEASONALOFFER21,211.54,1986.372575,1774.832575,Credit Card,Delhi
3,180333,1395204173,Other,60 and above,04/11/2020 04:41:57,Sports & Fitness,No,NaN,0.00,5695.612650,5695.612650,Debit Card,Delhi
4,447553,8009390577,Male,18-25,31/05/2022 17:00:32,Sports & Fitness,Yes,WELCOME5,439.92,2292.651500,1852.731500,Credit Card,Delhi
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54995,295864,5407639888,Other,25-45,23/02/2020 10:42:04,Electronics,Yes,SEASONALOFFER21,110.89,2819.907300,2709.017300,Debit Card,Other
54996,706435,1144029904,Other,18-25,12/07/2021 15:59:21,Electronics,Yes,SEASONALOFFER21,488.59,3891.303900,3402.713900,Cash on Delivery,Bangalore
54997,649435,9587323189,Male,45-60,02/08/2024 09:30:44,Home & Kitchen,Yes,NEWYEARS,417.63,4094.687500,3677.057500,Credit Card,Mumbai
54998,982183,5032564481,Female,45-60,05/08/2020 23:57:56,Beauty and Health,Yes,SEASONALOFFER21,204.56,3977.473500,3772.913500,Credit Card,Kolkata
54999,126691,9172953722,Male,25-45,21/07/2022 09:05:18,Beauty and Health,Yes,NEWYEARS,380.81,3703.581900,3322.771900,Credit Card,Mumbai

### DataCamp Exercises

In [ ]:
# Print the head of the sales DataFrame
print(sales.head())

# Print the info about the sales DataFrame
print(sales.info())

# Print the mean of weekly_sales
print(sales["weekly_sales"].mean())

# Print the median of weekly_sales
print(sales["weekly_sales"].median())

# -------------------------------------

# Print the maximum of the date column
print(sales["date"].max())

# Print the minimum of the date column
print(sales["date"].min())

# -------------------------------------

In [ ]:
"""Sorting"""
# dataframe = dataframe.sort_values("date")

In [47]:
""" Grouping """
# groupby()[]    -> group Gender by its items with/and Gross Amount
print(E_commerce.groupby("Gender")["Gross Amount"].agg(["max","min","mean"]))

print(E_commerce.groupby(["Gender","Product Category"])["Gross Amount"].agg(["max","min","mean"]))

print(E_commerce.groupby(["Gender","Product Category"])["Gross Amount"].median())


print(E_commerce.groupby(["Gender","Product Category"])[["Gross Amount","Discount Amount (INR)"]].median())


# pivot_table(value = "what you want to operate" , index = "what values grouped by")
print(E_commerce.pivot_table(values= "Gross Amount" , index = "Gender" ,aggfunc=["max","min","mean"]))
print(E_commerce.pivot_table(values= ["Gross Amount" , "Discount Amount (INR)"],index = ["Gender", "Product Category"] , aggfunc="median"))
# -----
# pivot_table(value = "what you want to operate" , index = "what values grouped by" , columns = "column name")
# that make table with columns
E_commerce.pivot_table(values = "Gross Amount" , index = "Gender" ,columns = "Product Category")
# That can fill missing(NaN) values too
E_commerce.pivot_table(values = "Gross Amount" , index = "Gender" ,columns = "Product Category", fill_value=0)

              max         min         mean
Gender
Female  8382.7968  136.454325  2993.200439
Male    8361.2256  147.963750  3004.773894
Other   8394.8256  143.130225  3040.683146
                                max         min         mean
Gender Product Category
Female Beauty and Health  8382.7968  136.454325  3031.043526
       Books              8024.4493  160.419000  2930.863877
       Clothing           8096.1048  140.461650  2969.847259
       Electronics        8334.0096  138.890850  2989.601536
       Home & Kitchen     8025.1416  158.448150  3063.665946
       Other              7706.5065  173.155500  2992.092575
       Pet Care           7619.8892  170.923500  2873.032427
       Sports & Fitness   8233.1424  162.417150  2967.284902
       Toys & Games       8365.1904  187.971000  3076.022454
Male   Beauty and Health  8194.6704  166.892000  3048.246657
       Books              8027.8786  148.402800  3001.810240
       Clothing           8361.2256  152.539200  2960.003326
       Electronics        8238.5352  153.390600  2980.956209
       Home & Kitchen     8301.7704  147.963750  3016.122472
       Other              8146.0680  159.895625  2952.249334
       Pet Care           7510.8264  160.436650  3017.192188
       Sports & Fitness   8083.1352  160.629000  3073.465665
       Toys & Games       7676.1902  172.822000  3128.164567
Other  Beauty and Health  8047.8048  156.028550  3037.391586
       Books              7822.9739  149.149350  3092.952811
       Clothing           8309.7672  152.747100  3022.765793
       Electronics        8135.5344  143.130225  3032.934388
       Home & Kitchen     8394.8256  157.251600  3021.615505
       Other              8111.4768  143.904600  3053.385311
       Pet Care           8322.4008  150.582600  3118.244332
       Sports & Fitness   8246.2296  156.874725  3079.450078
       Toys & Games       7305.5766  165.002400  3008.604250
Gender  Product Category
Female  Beauty and Health    2974.592500
        Books                2843.032500
        Clothing             2914.117500
        Electronics          2947.215300
        Home & Kitchen       3022.256650
        Other                2916.938200
        Pet Care             2759.811875
        Sports & Fitness     2916.019750
        Toys & Games         3048.778800
Male    Beauty and Health    2980.131000
        Books                2970.060000
        Clothing             2868.653700
        Electronics          2918.211450
        Home & Kitchen       2974.670500
        Other                2865.427950
        Pet Care             2880.683000
        Sports & Fitness     3035.263200
        Toys & Games         3160.220700
Other   Beauty and Health    2974.448675
        Books                3091.037250
        Clothing             2937.889500
        Electronics          2994.552000
        Home & Kitchen       2946.708400
        Other                2987.122500
        Pet Care             3174.651900
        Sports & Fitness     3046.212000
        Toys & Games         2833.963975
Name: Gross Amount, dtype: float64
                          Gross Amount  Discount Amount (INR)
Gender Product Category
Female Beauty and Health   2974.592500                  0.000
       Books               2843.032500                  0.000
       Clothing            2914.117500                 52.190
       Electronics         2947.215300                  0.000
       Home & Kitchen      3022.256650                 55.660
       Other               2916.938200                  0.000
       Pet Care            2759.811875                  0.000
       Sports & Fitness    2916.019750                 52.440
       Toys & Games        3048.778800                  0.000
Male   Beauty and Health   2980.131000                  0.000
       Books               2970.060000                 53.170
       Clothing            2868.653700                 60.090
       Electronics         2918.211450                  0.000
       Home & Kitchen      2974.670500                 51.340
       Other               2865.427950                 54.590
       Pet Care            2880.683000                  0.000
       Sports & Fitness    3035.263200                 50.250
       Toys & Games        3160.220700                  0.000
Other  Beauty and Health   2974.448675                  0.000
       Books               3091.037250                 54.080
       Clothing            2937.889500                  0.000
       Electronics         2994.552000                 51.560
       Home & Kitchen      2946.708400                 57.645
       Other               2987.122500                 64.930
       Pet Care            3174.651900                  0.000
       Sports & Fitness    3046.212000                  0.000
       Toys & Games        2833.963975                 71.505
                max          min         mean
       Gross Amount Gross Amount Gross Amount
Gender
Female    8382.7968   136.454325  2993.200439
Male      8361.2256   147.963750  3004.773894
Other     8394.8256   143.130225  3040.683146
                          Discount Amount (INR)  Gross Amount
Gender Product Category
Female Beauty and Health                  0.000   2974.592500
       Books                              0.000   2843.032500
       Clothing                          52.190   2914.117500
       Electronics                        0.000   2947.215300
       Home & Kitchen                    55.660   3022.256650
       Other                              0.000   2916.938200
       Pet Care                           0.000   2759.811875
       Sports & Fitness                  52.440   2916.019750
       Toys & Games                       0.000   3048.778800
Male   Beauty and Health                  0.000   2980.131000
       Books                             53.170   2970.060000
       Clothing                          60.090   2868.653700
       Electronics                        0.000   2918.211450
       Home & Kitchen                    51.340   2974.670500
       Other                             54.590   2865.427950
       Pet Care                           0.000   2880.683000
       Sports & Fitness                  50.250   3035.263200
       Toys & Games                       0.000   3160.220700
Other  Beauty and Health                  0.000   2974.448675
       Books                             54.080   3091.037250
       Clothing                           0.000   2937.889500
       Electronics                       51.560   2994.552000
       Home & Kitchen                    57.645   2946.708400
       Other                             64.930   2987.122500
       Pet Care                           0.000   3174.651900
       Sports & Fitness                   0.000   3046.212000
       Toys & Games                      71.505   2833.963975

Product Category,Beauty and Health,Books,Clothing,Electronics,Home & Kitchen,Other,Pet Care,Sports & Fitness,Toys & Games
Gender,,,,,,,,,
Female,3031.043526,2930.863877,2969.847259,2989.601536,3063.665946,2992.092575,2873.032427,2967.284902,3076.022454
Male,3048.246657,3001.810240,2960.003326,2980.956209,3016.122472,2952.249334,3017.192188,3073.465665,3128.164567
Other,3037.391586,3092.952811,3022.765793,3032.934388,3021.615505,3053.385311,3118.244332,3079.450078,3008.604250