# **Explicit Indexes**

In [1]:
import pandas as pd
df = pd.read_csv("/content/project1_df.csv")

In [2]:
df.index

RangeIndex(start=0, stop=55000, step=1)

In [3]:
df.columns

Index(['CID', 'TID', 'Gender', 'Age Group', 'Purchase Date',
       'Product Category', 'Discount Availed', 'Discount Name',
       'Discount Amount (INR)', 'Gross Amount', 'Net Amount',
       'Purchase Method', 'Location'],
      dtype='object')

In [4]:
# Setting a column as the index
df_index = df.set_index("CID")

In [6]:
df_index.head(2)

,TID,Gender,Age Group,Purchase Date,Product Category,Discount Availed,Discount Name,Discount Amount (INR),Gross Amount,Net Amount,Purchase Method,Location
CID,,,,,,,,,,,,
943146,5876328741,Female,25-45,30/08/2023 20:27:08,Electronics,Yes,FESTIVE50,64.30,725.304000,661.004000,Credit Card,Ahmedabad
180079,1018503182,Male,25-45,23/02/2024 09:33:46,Electronics,Yes,SEASONALOFFER21,175.19,4638.991875,4463.801875,Credit Card,Bangalore

In [7]:
# reset the index
df_index.reset_index()

,CID,TID,Gender,Age Group,Purchase Date,Product Category,Discount Availed,Discount Name,Discount Amount (INR),Gross Amount,Net Amount,Purchase Method,Location
0,943146,5876328741,Female,25-45,30/08/2023 20:27:08,Electronics,Yes,FESTIVE50,64.30,725.304000,661.004000,Credit Card,Ahmedabad
1,180079,1018503182,Male,25-45,23/02/2024 09:33:46,Electronics,Yes,SEASONALOFFER21,175.19,4638.991875,4463.801875,Credit Card,Bangalore
2,337580,3814082218,Other,60 and above,06/03/2022 09:09:50,Clothing,Yes,SEASONALOFFER21,211.54,1986.372575,1774.832575,Credit Card,Delhi
3,180333,1395204173,Other,60 and above,04/11/2020 04:41:57,Sports & Fitness,No,NaN,0.00,5695.612650,5695.612650,Debit Card,Delhi
4,447553,8009390577,Male,18-25,31/05/2022 17:00:32,Sports & Fitness,Yes,WELCOME5,439.92,2292.651500,1852.731500,Credit Card,Delhi
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54995,295864,5407639888,Other,25-45,23/02/2020 10:42:04,Electronics,Yes,SEASONALOFFER21,110.89,2819.907300,2709.017300,Debit Card,Other
54996,706435,1144029904,Other,18-25,12/07/2021 15:59:21,Electronics,Yes,SEASONALOFFER21,488.59,3891.303900,3402.713900,Cash on Delivery,Bangalore
54997,649435,9587323189,Male,45-60,02/08/2024 09:30:44,Home & Kitchen,Yes,NEWYEARS,417.63,4094.687500,3677.057500,Credit Card,Mumbai
54998,982183,5032564481,Female,45-60,05/08/2020 23:57:56,Beauty and Health,Yes,SEASONALOFFER21,204.56,3977.473500,3772.913500,Credit Card,Kolkata
54999,126691,9172953722,Male,25-45,21/07/2022 09:05:18,Beauty and Health,Yes,NEWYEARS,380.81,3703.581900,3322.771900,Credit Card,Mumbai

In [8]:
df_index = df.set_index("CID")

In [9]:
df_index.head(2)

,TID,Gender,Age Group,Purchase Date,Product Category,Discount Availed,Discount Name,Discount Amount (INR),Gross Amount,Net Amount,Purchase Method,Location
CID,,,,,,,,,,,,
943146,5876328741,Female,25-45,30/08/2023 20:27:08,Electronics,Yes,FESTIVE50,64.30,725.304000,661.004000,Credit Card,Ahmedabad
180079,1018503182,Male,25-45,23/02/2024 09:33:46,Electronics,Yes,SEASONALOFFER21,175.19,4638.991875,4463.801875,Credit Card,Bangalore

In [10]:
# Dropping an index
df_index.reset_index(drop = True)

,TID,Gender,Age Group,Purchase Date,Product Category,Discount Availed,Discount Name,Discount Amount (INR),Gross Amount,Net Amount,Purchase Method,Location
0,5876328741,Female,25-45,30/08/2023 20:27:08,Electronics,Yes,FESTIVE50,64.30,725.304000,661.004000,Credit Card,Ahmedabad
1,1018503182,Male,25-45,23/02/2024 09:33:46,Electronics,Yes,SEASONALOFFER21,175.19,4638.991875,4463.801875,Credit Card,Bangalore
2,3814082218,Other,60 and above,06/03/2022 09:09:50,Clothing,Yes,SEASONALOFFER21,211.54,1986.372575,1774.832575,Credit Card,Delhi
3,1395204173,Other,60 and above,04/11/2020 04:41:57,Sports & Fitness,No,NaN,0.00,5695.612650,5695.612650,Debit Card,Delhi
4,8009390577,Male,18-25,31/05/2022 17:00:32,Sports & Fitness,Yes,WELCOME5,439.92,2292.651500,1852.731500,Credit Card,Delhi
...,...,...,...,...,...,...,...,...,...,...,...,...
54995,5407639888,Other,25-45,23/02/2020 10:42:04,Electronics,Yes,SEASONALOFFER21,110.89,2819.907300,2709.017300,Debit Card,Other
54996,1144029904,Other,18-25,12/07/2021 15:59:21,Electronics,Yes,SEASONALOFFER21,488.59,3891.303900,3402.713900,Cash on Delivery,Bangalore
54997,9587323189,Male,45-60,02/08/2024 09:30:44,Home & Kitchen,Yes,NEWYEARS,417.63,4094.687500,3677.057500,Credit Card,Mumbai
54998,5032564481,Female,45-60,05/08/2020 23:57:56,Beauty and Health,Yes,SEASONALOFFER21,204.56,3977.473500,3772.913500,Credit Card,Kolkata
54999,9172953722,Male,25-45,21/07/2022 09:05:18,Beauty and Health,Yes,NEWYEARS,380.81,3703.581900,3322.771900,Credit Card,Mumbai

In [14]:
df_index = df.set_index("TID")

In [19]:
# Indexes make subsetting simpler
df_index.loc[[5876328741,5876328741 ]]

,CID,Gender,Age Group,Purchase Date,Product Category,Discount Availed,Discount Name,Discount Amount (INR),Gross Amount,Net Amount,Purchase Method,Location
TID,,,,,,,,,,,,
5876328741,943146,Female,25-45,30/08/2023 20:27:08,Electronics,Yes,FESTIVE50,64.3,725.304,661.004,Credit Card,Ahmedabad
5876328741,943146,Female,25-45,30/08/2023 20:27:08,Electronics,Yes,FESTIVE50,64.3,725.304,661.004,Credit Card,Ahmedabad

,CID,Gender,Age Group,Purchase Date,Product Category,Discount Availed,Discount Name,Discount Amount (INR),Gross Amount,Net Amount,Purchase Method,Location
TID,,,,,,,,,,,,
5876328741,943146,Female,25-45,30/08/2023 20:27:08,Electronics,Yes,FESTIVE50,64.3,725.304,661.004,Credit Card,Ahmedabad
5876328741,943146,Female,25-45,30/08/2023 20:27:08,Electronics,Yes,FESTIVE50,64.3,725.304,661.004,Credit Card,Ahmedabad

In [21]:
# Index values don't need to be unique
df_index.reset_index()
df_index = df_index.set_index("Product Category")

In [22]:
# Subsetting on duplicated index values
df_index.loc["Electronics"]

,CID,Gender,Age Group,Purchase Date,Discount Availed,Discount Name,Discount Amount (INR),Gross Amount,Net Amount,Purchase Method,Location
Product Category,,,,,,,,,,,
Electronics,943146,Female,25-45,30/08/2023 20:27:08,Yes,FESTIVE50,64.30,725.304000,661.004000,Credit Card,Ahmedabad
Electronics,180079,Male,25-45,23/02/2024 09:33:46,Yes,SEASONALOFFER21,175.19,4638.991875,4463.801875,Credit Card,Bangalore
Electronics,668787,Male,25-45,08/10/2023 16:59:52,No,NaN,0.00,5593.935600,5593.935600,PhonePe UPI,Delhi
Electronics,933551,Female,18-25,14/12/2022 20:13:45,No,NaN,0.00,1901.796400,1901.796400,Credit Card,Delhi
Electronics,629298,Other,45-60,02/11/2021 15:37:38,No,NaN,0.00,988.172900,988.172900,Google Pay UPI,Chennai
...,...,...,...,...,...,...,...,...,...,...,...
Electronics,903683,Female,25-45,22/03/2024 23:52:20,Yes,NEWYEARS,456.01,4733.826250,4277.816250,Paytm UPI,Mumbai
Electronics,907365,Male,25-45,12/05/2023 15:48:26,No,NaN,0.00,927.384000,927.384000,Debit Card,Bangalore
Electronics,639165,Male,25-45,15/05/2022 20:32:26,No,NaN,0.00,4489.956500,4489.956500,Credit Card,Kolkata
Electronics,295864,Other,25-45,23/02/2020 10:42:04,Yes,SEASONALOFFER21,110.89,2819.907300,2709.017300,Debit Card,Other
Electronics,706435,Other,18-25,12/07/2021 15:59:21,Yes,SEASONALOFFER21,488.59,3891.303900,3402.713900,Cash on Delivery,Bangalore

In [31]:
df_index.reset_index()

,Gender,Purchase Method,CID,Age Group,Purchase Date,Discount Availed,Discount Name,Discount Amount (INR),Gross Amount,Net Amount,Location
0,Female,Credit Card,943146,25-45,30/08/2023 20:27:08,Yes,FESTIVE50,64.30,725.304000,661.004000,Ahmedabad
1,Male,Credit Card,180079,25-45,23/02/2024 09:33:46,Yes,SEASONALOFFER21,175.19,4638.991875,4463.801875,Bangalore
2,Other,Credit Card,337580,60 and above,06/03/2022 09:09:50,Yes,SEASONALOFFER21,211.54,1986.372575,1774.832575,Delhi
3,Other,Debit Card,180333,60 and above,04/11/2020 04:41:57,No,NaN,0.00,5695.612650,5695.612650,Delhi
4,Male,Credit Card,447553,18-25,31/05/2022 17:00:32,Yes,WELCOME5,439.92,2292.651500,1852.731500,Delhi
...,...,...,...,...,...,...,...,...,...,...,...
54995,Other,Debit Card,295864,25-45,23/02/2020 10:42:04,Yes,SEASONALOFFER21,110.89,2819.907300,2709.017300,Other
54996,Other,Cash on Delivery,706435,18-25,12/07/2021 15:59:21,Yes,SEASONALOFFER21,488.59,3891.303900,3402.713900,Bangalore
54997,Male,Credit Card,649435,45-60,02/08/2024 09:30:44,Yes,NEWYEARS,417.63,4094.687500,3677.057500,Mumbai
54998,Female,Credit Card,982183,45-60,05/08/2020 23:57:56,Yes,SEASONALOFFER21,204.56,3977.473500,3772.913500,Kolkata
54999,Male,Credit Card,126691,25-45,21/07/2022 09:05:18,Yes,NEWYEARS,380.81,3703.581900,3322.771900,Mumbai

In [34]:
# Multi-level indexes a.k.a. hierarchical indexes
df = df.set_index(["Gender","Location"])

In [36]:
df.loc[["Male","Mumbai"]]

KeyError: "['Mumbai'] not in index"